local component = require("component")
local serial = require("serialization")
local data = component.data

os.execute("cp /startup /normal_wd")

local pl = io.open("/lib/autopilot/planet-list.lua", "w")
pl:write(inflate(decode64("eJx10LEOgyAQBuC9T8HmIomYWqc+SdPhrKRQLBiEJsT47rUq6ZnShdzw5f+Ps9x5q8l4IOSSOd6ZIbuSMxnLqihyUlan+fnMU74IBYMIQa2GIcQQcuCMkZr/KsrqL2vhbhoQq6I7hcKEcZGwfyaAfUlNjzEKOdQnO/+MSXVStJz3dOjhtq2OFEV1XLfGJrp2v3PBCaM3VacPpYy1soFN7aLw0R+glI996c2Fn5MUxJtjtczTYXoDgQ13OQ=="))
pl:close(pl)

local nc = io.open("/lib/autopilot/navConf.lua", "w")
nc:write(inflate(decode64("eJwrSi0pLcpTqOZSUEhLzClO1QEylPJSy5V0uGoBgxQISA=="))
nc:close(nc)

local s = io.open("/startup", "w")
s:write(inflate(decode64(""))
s:close(s)
